image:
  repository: mahalath/complete-devops-project
  tag: da9a9e3
  pullPolicy: IfNotPresent
service: 
  type: ClusterIP 
  port: 8080
ingress:
  enabled: false
httpRoute:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false