image:
  repository: mahalath/complete-devops-project
  tag: cf88c3a
  pullPolicy: IfNotPresent
service: 
  type: Cluster IP 
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscalling:
  enabled: false